jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.7.3.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-hightide-8.1.8.v20121106.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.13.1.jar"
http_port: 10080
https_port: 10443
ruby_version: 1.9
app_type: rack
keystore: "etc/fake.p12"
keystore_password: "foobar"
